# Configure SonarCloud analysis scope
sonar.sources=backend/src/main,frontend/src
sonar.tests=backend/src/test

# Exclusions from all analysis
sonar.exclusions=test/**/*,reporters/**/*,backend/target/**/*,**/node_modules/**/*,backend/src/test/**/*,docs/**/*,postman/**/*,.github/**/*,*.md,**/*.md,backend/src/main/resources/**/*
sonar.test.exclusions=backend/src/test/**/*

# Exclusions from duplication checks
sonar.cpd.exclusions=test/**/*,reporters/**/*,backend/target/**/*,**/node_modules/**/*,backend/src/test/**/*,docs/**/*,postman/**/*,.github/**/*,*.md,**/*.md,backend/src/main/resources/**/*
