# Configure SonarCloud analysis scope
sonar.sources=backend/src/main,frontend/src
sonar.tests=backend/src/test

# Exclusions from all analysis
sonar.exclusions=test/resources/**/*,reporters/**/*,backend/target/**/*,**/node_modules/**/*

# Exclusions from duplication checks
sonar.cpd.exclusions=test/resources/**/*,reporters/**/*,backend/target/**/*,**/node_modules/**/*
